### ISSUE TITLE
This repository is the most fascist thing I've seen in a while

### ISSUE THREAD

**Issue by Cydhra** [racismbreaker/racismbreaker#10]
Collecting accounts, names and data of people not complying to an arbitrarily chosen world view to this repository? I mean, I guess you got good intentions, but this sure sounds like the very same fascist system you seak to destroy.
Spread awareness, not hateful exclusion.

**Comment by YhvrWasTaken** [comment]
HAHA What the actual hell? Now they're editing your message to try to censor you? God, I love this.

**Comment by JasonHK** [comment]
> HAHA What the actual hell? Now they're editing your message to try to censor you? God, I love this.

Traces was usually left when you trying to censor something using Git. This just show how stupid these left wing are.

**Comment by flying-sheep** [comment]
psst, does

> It's really that easy, racism is no more thanks to us awesome woke javascript software engineers!

sound like it’s to be taken at face value to you?

yes? maybe you should go outside and talk to people sometimes. you can do so from a safe 1.5m distance if you’re worried about corona.
